### PR TITLE
Update Auto-generated Ocean User's Guide

### PR DESCRIPTION
**Pull request by xylar**
This was generated with the latest MPAS-Ocean registry from E3SM's `master` branch and from this updated tool:
https://github.com/xylar/MPAS-Tools/blob/update-parse-registry/python_scripts/namelist_generation/parse_xml_registry.py

### CODE REVIEW

**Review by mark-petersen — APPROVED** [review]
I reviewed the document and everything is in order. Thank you for this! My only comment is to update the version and date on the first page.

**Comment by xylar** [comment]
@mark-petersen, I generated a new registry using this E3SM hash: https://github.com/E3SM-Project/E3SM/commit/cd4074582ed45bf81f522dd6b2c57bb93ce620a4

This is essentially identical to the 3.0.0 tag except for a few formatting fixes and clarifications in descriptions of namelist options.

I updated the auto-generated documentation with that version:
[mpas_ocean_users_guide.pdf](https://github.com/MPAS-Dev/MPAS-Documents/files/15140047/mpas_ocean_users_guide.pdf)

**Comment by mark-petersen** [comment]
One more. Please delete the current text of the forward page, including the names at the bottom. This revised text is important for anyone who happens to see this. Please simply use this text for the Forward:

This User's Guide is for the Model for Prediction Across Scales-Ocean (MPAS-Ocean), the ocean component of the Energy Exascale Earth System Model (E3SM), developed by the U.S. Department of Energy. Herein we describe the equations, namelist options, and variables for MPAS-Ocean. These settings apply to both the standalone ocean-only version of MPAS-Ocean, and E3SM version that is coupled to the atmosphere, sea ice, land ice, land and river components. 

The MPAS-Ocean code for both standalone and coupled is housed in the repository [https://github.com/E3SM-Project/E3SM](https://github.com/E3SM-Project/E3SM), within the directory `components/mpas-ocean`. The standalone executable may be built within that directory using the make command with the required libraries, as described in Chapter 1 of this guide.

Documentation for the E3SM coupled climate model may be found on the [E3SM docs pages](https://docs.e3sm.org/E3SM/), the  [E3SM Documentation webpage](https://acme-climate.atlassian.net/wiki/spaces/DOC/overview?homepageId=1931641291), or the [E3SM repository homepage](https://github.com/E3SM-Project/E3SM).

**Comment by xylar** [comment]
@mark-petersen and @alicebarthel, here is the latest version as requested:
[mpas_ocean_users_guide.pdf](https://github.com/MPAS-Dev/MPAS-Documents/files/15140219/mpas_ocean_users_guide.pdf)

Here is a screenshot of the forward, for your convenience:
Screenshot from 2024-04-27 16-46-41

**Comment by mark-petersen** [comment]
I forgot to merge this before. Thanks @xylar, this was very useful for the documentation and tutorial.

**Pull request merged**
